version: 1
labels:
  - label: "WIP"
    title: "^WIP:.*"
  - label: "feature"
    branch: "^feature/.*"
  - label: "bugfix"
    branch: "^bugfix/.*"
  - label: "hotfix"
    branch: "^hotfix/.*"
  - label: "enh"
    branch: "^enhance/.*"
  - label: "style"
    branch: "^style/*"
  - label: "docs"
    branch: "^docs/*"
  - label: "release"
    branch: "^release/v[0-9]+[.][0-9]+[.][0-9]+"
  - label: "need-to-change-branch-name"
    branch: "^(?!^feature/.*$)(?!^bugfix/.*$)(?!^hotfix/.*$)(?!^enhance/.*$)(?!^style/.*$)(?!^docs/.*$).*$"
