# RL^2 direction target reward configs

# General setup
# -------------
# Number of tasks for meta-train
train_tasks: 2

# Number of tasks for meta-test
test_tasks: 2

# Number of hidden units in neural networks
hidden_dim: 100

# MAML setup
# ----------
maml_params:
    # Number of training iterations
    train_iters: 1000
    # Number of task samples for training
    num_sample_tasks: 5
    # Number of samples to train
    train_samples: 200
    # Maximum step for the environment
    max_step: 200
    # Number of samples to test
    test_samples: 200
    # Number of inner adaptation iterations for the MAML algorithm
    inner_grad_iters: 1
    # Learning rate of inner adaptation
    inner_learning_rate: 0.1
    # Number of PPO iterations per each meta-update iteration
    outer_grad_iters: 5
    # Learning rate of PPO losses
    outer_learning_rate: 0.001

# PPO setup
# ---------
ppo_params:
    # PPO clip parameter
    clip_param: 0.3
    # coefficient of the value function 
    vf_loss_coeff: 0.5
    # Learning rate of value function
    vf_learning_rate: 0.001


