# Velocity target reward configs

# General setup
# -------------
# Number of tasks for meta-train
train_tasks: 300

# Number of tasks for meta-test
test_tasks: 15

# Number of hidden units in neural networks
hidden_dim: 64

# RL^2 setup
# ----------
rl2_params:
    # Number of training iterations
    num_iterations: 1000
    # Number of samples to train
    num_samples: 1200
    # Maximum step for the environment
    max_step: 200
    # Number of task samples for training
    meta_batch_size: 10
    # Number of early stopping conditions
    num_stop_conditions: 3
    # Goal value used to early stopping condition
    stop_goal: 25

# PPO setup
# ---------
ppo_params:
    # Discount factor
    gamma: 0.99
    # Number of epochs per iteration
    num_epochs: 10
    # Number of minibatch within each epoch
    mini_batch_size: 32
    # PPO clip parameter
    clip_param: 0.3
    # Learning rate of PPO losses
    learning_rate: 0.0001
